[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "heatlift"
version = "0.0.1"
dependencies = [
  "numpy",
  "scipy", 
  "hirola"
]

[tool.setuptools]
include-package-data = true